name: Semgrep SAST

on:
  push:
    branches: [ "**" ]

jobs:
  semgrep:
    name: Run Semgrep Scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: semgrep scan --config auto --verbose